### PR TITLE
fix map marshaling

### PR DESCRIPTION
**Pull request by leveretka**
We faced a problem with map serialization. Current code serializes map as a packed repeated value which is different from what we see in serialization from scala/java generated sources. 

Please take a look into it, cause we are planning to use it in the nearest future.

Thanks.

### CODE REVIEW

**Comment by cretz** [comment]
Thanks! I will investigate.

**Comment by cretz** [comment]
Thanks for the report, I made the fix in a bit of a different way and renamed some things. It is fixed in master and the runtime is deployed to https://oss.sonatype.org/content/repositories/snapshots as version 0.3.0-SNAPSHOT. I'll leave this open until I release 0.3.0.

**Comment by leveretka** [comment]
Cool! Thanks :)

**Comment by cretz** [comment]
0.3.0 released

**Pull request closed without merging**
