### PR TITLE
Build an artifact compatible with the protobuf gradle plugin

### LINKED ISSUE #18: Provide a protoc-gen-kotlin maven artifact that's compatible with the protobuf gradle plugin
The protobuf gradle plugin supports downloading `protoc` plugins from maven central: https://github.com/google/protobuf-gradle-plugin#locate-external-executables. This would make it much easier to use `pb-and-k` in a gradle build since the `protoc-gen-kotlin` binary wouldn't have to be compiled/installed manually.

The requirements to enable this are:

* Package `protoc-gen-kotlin` as a self-executable jar. For example, you can use something like the [Spring Boot Gradle Plugin](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/) to create a [fully executable archive](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#packaging-executable-configuring-launch-script).

* Distribute the self-executable jar on maven central with a custom classifier (the protobuf gradle plugin doesn't provide any way to use an artifact with an empty classifier).

For example, if the self-executable jar is distributed as the `com.github.cretz.pbandk:protoc-gen-kotlin` artifact with a `jvm8` classifier, then it could be used with the protobuf gradle plugin like this:

```groovy
 protobuf {
    plugins {
        kotlin {
            artifact = 'com.github.cretz.pbandk:protoc-gen-kotlin:0.3.0:jvm8@jar'
        }
    }
    ...
}
```

### PR DESCRIPTION
**Pull request by garyp**
This ended up being quicker to implement than I thought. Fixes #18.

### CODE REVIEW

**Comment by Globegitter** [comment]
@cretz any chance to get this included?

**Comment by cretz** [comment]
Hrmm, @garyp and @Globegitter - are there any unintended side effects of anyone else using this library by using the spring framework boot plugin? Does it effect the final JAR or the project in anyway wrt dependencies?

I don't really work on this project much anymore, so I can blindly accept the merge if there are no unintended consequences, but can't really promise I'll publish a versioned release any time soon.

**Comment by garyp** [comment]
Hi @cretz. Sorry, just catching up after vacation. I don't believe this change will impact anyone using this library. It adds an additional JAR artifact (with the `jvm8` classifier), but does not change the default JAR artifact that is produced, nor the POM file.

Regarding the project's maintenance, we're starting to use `pb-and-k` at my company and we have an actively maintained fork: https://github.com/streem/pb-and-k. We've fixed some bugs, added some ease-of-use improvements to the generated code, and have started on proto3 JSON support. If you're interested, we'd be glad to take over maintenance of `pb-and-k`.

**Comment by cretz** [comment]
> If you're interested, we'd be glad to take over maintenance of pb-and-k.

@garyp - I would love to link to that maintained fork (I'd rather it stay over there instead of y'all having to maintain it under my GH name/org). I can't really work on this repo, so it'd be ideal if yours became the go-to. I even gladly give my blessing for y'all to change the package name, readme, copyright, remove the forked-from link, etc. Just let me know if that sounds ok, then I'll update this README with a notice pointing you y'all's repo.

**Comment by garyp** [comment]
@cretz If you wanted to update the README to point at https://github.com/streem/pbandk (note that our repo is lacking the dashes in the name), that'd be great. Thanks.

**Comment by cretz** [comment]
@garyp - Done! Thanks!

**Pull request closed without merging**
