### PR TITLE
Add bootjar so that codegenerator can be included as artifact

### PR DESCRIPTION
**Pull request by phcoder**
This allows inclusing of pb-and-k from maven without any need of local
installation

### CODE REVIEW

**Comment by cretz** [comment]
I don't really use spring (and many others don't either) and in general I'm not wanting to infect my build script with it. Assuming I understand the purpose here, why use maven to get the JAR if you need it all self-contained? If you want a self-contained release, there are release packages downloadable from the release area.

Can you help me understand why you need a self-contained executable boot jar instead of the executable already provided by assemble?

**Comment by phcoder** [comment]
Many projects are distributed as gradle projects. The expectation is that you can compile them by typing './gradlew assembleDebug' without preinstalling anything. Having to preinstall pb-and-k breaks this expectation with this patch I can put in build.gradle
    plugins {
        kotlin {
            artifact '....'
        }
    }
and gradle will automatically download pb-and-k. Unfortunately this doesn't work with standard jar.
Alternative is to have and distribute throught maven native compilations of protoc-gen-kotlin for linux-i386, linux-x64, osx-i386, osx-x64, windows. I have seen protoc-gen-kotlin-native but so far didn't manage to even compile it:
phcoder@penguin:~/pb-and-k$ ./gradlew :protoc-gen-kotlin:protoc-gen-kotlin-native

.....
* What went wrong:
Task 'protoc-gen-kotlin-native' not found in project ':protoc-gen-kotlin'.

**Comment by phcoder** [comment]
Yes "Protobuf code generator in Kotlin Native for easier importing" is exactly what I want. Maybe it would make sense if I prepare the PR to make "Protobuf code generator in Kotlin Native" work?

**Comment by cretz** [comment]
@phcoder - Sure. The JVM one works fine btw, but a native one would be nice, but it's not a requirement to use the project in any way. I have already done most of the abstraction as common code at `protoc-gen-kotlin/protoc-gen-kotlin-common`. Just implement [Platform.kt](https://github.com/cretz/pb-and-k/blob/cf8cb836e501ed95a05dd6cc40f08d2557ecca2c/protoc-gen-kotlin/protoc-gen-kotlin-common/src/main/kotlin/pbandk/gen/Platform.kt) for native in `protoc-gen-kotlin/protoc-gen-kotlin-native` the same way [I did for the JVM](https://github.com/cretz/pb-and-k/blob/cf8cb836e501ed95a05dd6cc40f08d2557ecca2c/protoc-gen-kotlin/protoc-gen-kotlin-jvm/src/main/kotlin/pbandk/gen/Platform.kt). You can even just throw from the `serviceGenerator` method for now.

**Comment by phcoder** [comment]
@cretz It seems thatit's possible to remove dependency on platform protobuf libraries. Trying to do it, let's see how it goes. How important is it to keep api source-compatible? I'd like to make Marshaller an abstract class with ByteArrayMarshaller available on all the platforms and then platform providing only functions to read/write from stream

**Comment by phcoder** [comment]
I'm implementing #7 in pure kotlin. Wait couple of days

**Pull request closed without merging**
